language: php
dist: xenial
sudo: required
php:
  - '7.2'
  - '7.3'
  - '7.4'
before_script:
  - composer install --no-interaction
script:
  - "./vendor/bin/phpunit --coverage-clover=coverage.xml"
after_script:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - vendor
